import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  finalizedLedgerPath,
  resolvePreselectedPeriodId,
} from '../src/pages/payroll/finalizedNavigation.ts';

test('finalizedLedgerPath: generates the Ledger path with the period id preselected', () => {
  assert.equal(finalizedLedgerPath(9042), '/payroll/ledger?period_id=9042');
});

test('resolvePreselectedPeriodId: round-trips the id generated by finalizedLedgerPath (period identity preserved)', () => {
  const path = finalizedLedgerPath(9042);
  const query = path.split('?')[1];
  const params = new URLSearchParams(query);
  assert.equal(resolvePreselectedPeriodId(params), 9042);
});

test('resolvePreselectedPeriodId: null when the param is absent', () => {
  assert.equal(resolvePreselectedPeriodId(new URLSearchParams()), null);
});

test('resolvePreselectedPeriodId: null for a non-numeric or non-positive value, never throws', () => {
  assert.equal(resolvePreselectedPeriodId(new URLSearchParams('period_id=abc')), null);
  assert.equal(resolvePreselectedPeriodId(new URLSearchParams('period_id=-5')), null);
  assert.equal(resolvePreselectedPeriodId(new URLSearchParams('period_id=0')), null);
  assert.equal(resolvePreselectedPeriodId(new URLSearchParams('period_id=12.5')), null);
});
